### ISSUE TITLE
Scale up logic using targetMessagesPerWorker

### ISSUE THREAD

**Issue by AmeerAssi** [practo/k8s-worker-pod-autoscaler#101]
I am using WPA in my service, where my pods are by design taking a lot of time to be initialized (~15 mins).
as I need to start initializing new pods immediately once needed according to the queue size, I've used this configuration:
--resync-period=60
--wpa-threads=10
--aws-regions=us-east-2
--sqs-short-poll-interval=20
--sqs-long-poll-interval=20

so in a short time the auto-scaler will recognize the need of scaling, then the pods will start initializing.

for simplicity lets say one worker can handle 10 jobs, so if I have 100 messages in the queue then I will need 10 workers.
the behavior I get is:
in the first loop the algorithm decides to scale up to 10 workers as expected
in the second loop the queue messages are still ~100 as the workers did not start yet, so the algorithm decides to scale up to 100 this time.

looking on the code logic in file https://github.com/practo/k8s-worker-pod-autoscaler/blob/59d0d487fa22f8121a7a123584e33b09dba04896/pkg/controller/controller.go, I see this:
![image](https://user-images.githubusercontent.com/31182104/87256235-80e8c400-c499-11ea-951f-f7c076af44ba.png)
 
my understanding that if I decided on targetMessagesPerWorker, I should get always 10 workers for 100 messages in my case, but it looks like the algorithm still looks on the current workers count.

Is there a way to keep the behavior as constant without depending on currently running pods, like this (some flag that will "remove" the if, so the scale will be always a constant and not depending on the current running workers):
![image](https://user-images.githubusercontent.com/31182104/87256295-e6d54b80-c499-11ea-92bc-5d541599aa59.png)

also the flag name giving this meaning, that the scale logic is simply affected by the queue size where you configure messages count that can be handled by single worker.

appreciate your help!

**Comment by alok87** [comment]
That multiplication is there so that, if there is a huge backlog we scale from 2 to max or some higher number directly instead of going there in steps. Solving #67 should solve your problem. Can we close this as a dup of #67 ?

**Comment by AmeerAssi** [comment]
thanks for the answer.
solving #67 will partially fix my case, the concept I am bringing here is that I've assigned X jobs to single processor, I don't mind how time will take this processor to process these X jobs, but I do mind about how many processors will be scaled up based on these X jobs (as I am paying for every processor at the end).
I think the best way will be to have an option of disabling the "fast scale up". and to have an ability to scale based on the queue size an exact number of messages per pod.
what do you think?

**Comment by alok87** [comment]
@AmeerAssi current_workers=available replicas in kubernetes deployment or replicaset. So the second loop will still result in 10 workers, unless your backlog also increased.

- queueMessages(unprocessed jobs/messages)=100, current_workers=0, targetMessagesPerWorker=10
   desired_workers = (100/10) = 10 (first loop)
   desired_workers = (100/10) = 10 (second loop, since your pod takes 15 minutes to come up)

- queueMessages(unprocessed jobs/messages)=100, current_workers=2, targetMessagesPerWorker=10
   desired_workers = (100/10) * 2 = 20 (first loop)
   desired_workers = (100/10) * 2 = 20 (second loop, since your pod takes 15 minutes to come up)

**Comment by AmeerAssi** [comment]
thanks again for the answer @alok87 .
sorry maybe I was not clear.
yes I agree this will fix the specific case here, but my scenario is that some jobs may take a lot of time to be processed too.
so what will happen is:
1. scale up request will start in the first loop and after 15 mins I will have 10 workers.
2. the 10 workers are expected to finish the assigned work in 1 hours, I want to have 10 workers running for an hour until the works finishes.
3. the auto scaler in the next loop (20 secs) will recognize 10 workers then scale to 100 workers, as the number of messages may be still close to 100 as I expect the work to finish in an hour.
4. even worse, after 15 mins (30 mins of scale start) the messages will be ~50 in the queue, then the auto-scaler will decide to scale up to 100*5 -> 500.

so after an hour of running, I expected to have 10 workers running for an hour to finish the 100 jobs, but the actual result is that I am getting more than 100 workers.

another possible scenario, that I didn't test:
1. I will have 10 workers running after 15 mins.
2. new 100 messages will arrive to the queue, which my expectation to assign another 10 workers for them.
3. the auto-scaler will recognize 10 workers running, and will assign 100 workers for the new 100 messages.

my thinking that the number of running workers, should not be relevant in a scenario that I want to assign 1 worker for X jobs.
as after a scale I can get new X jobs, which according to the needed behavior should trigger 1 worker scale up, but according to the implementation it will trigger current_workers scale per X jobs.

**Comment by justjkk** [comment]
Hi @AmeerAssi, thanks for pointing this out. In our initial implementation we used `targetMessagesPerWorker` more or less as a heuristic to determine **how quickly** WPA scales from min to max and not **how much** it scales based on backlog. The idea is to increase capacity till all jobs are picked up by workers. The original [blog post](https://medium.com/practo-engineering/launching-worker-pod-autoscaler-3f6079728e8b) also assumes this behavior:

    WPA will start scaling example-deployment from 0 to 30 if the messages in the queue are greater than 150.

As we made more changes like [partial scale down](https://github.com/practo/k8s-worker-pod-autoscaler/pull/60), [scaling based on throughput](https://github.com/practo/k8s-worker-pod-autoscaler/pull/62) and [fixing edge cases](https://github.com/practo/k8s-worker-pod-autoscaler/issues/73), we realized  that `targetMessagesPerWorker` is interpreted by more or less everyone(even us) as the ratio of messages to workers(probably because of the name and the lack of clarity in documentation). The impact for us was still limited since max is not set to a high value in our setup and so temporarily running more workers than required was fine.

We have two options:
1. Change the current behavior by scaling up to target workers instead of max workers. `targetMessagesPerWorker` is defined to be the ratio of queued jobs to workers required to match them.
2. Preserve the current behavior of scaling to max and instead deprecate `targetMessagesPerWorker` in favor of a different name that does the same job but is clear in the meaning like `scaleUpSpeed`(!?).

After discussing internally, we think option 1 is the least problematic approach even though there is a risk of breaking backward compatibility. PR #105 is created as a result. Please let us know your thoughts.

**Comment by AmeerAssi** [comment]
Hi @justjkk,
thank you for the detailed answer and for your time investigating this.
to make sure I understand correctly, the first option means:
once  targetMessagesPerWorker is configured to X, the number of workers will be NumOfMessages/X?

regarding NumOfMessages in queue considered in scaling for SQS case, is it the sum of "visible messages" and "not visible messages" (during processing)? or do you consider only "visible messages"?

thanks!

**Comment by justjkk** [comment]
Yes, the number of workers calculation is as you mentioned([ref](https://github.com/practo/k8s-worker-pod-autoscaler/pull/105/files#diff-3c862eb54a8e0e161b534e0c67e5379eR638-R640)). The NumOfMessages includes both Visible and not visible messages(since [v1](https://github.com/practo/k8s-worker-pod-autoscaler/pull/86) release).

**Comment by alok87** [comment]
@justjkk @AmeerAssi please review this test case: https://github.com/practo/k8s-worker-pod-autoscaler/pull/105/commits/0beb14f5aa294998e6327d2a24bae8a7fadf7fe4

**Comment by AmeerAssi** [comment]
@alok87  the behavior in the test case looks great for me.
@justjkk  and @alok87 thank you very much for the efforts.
I'll appreciate if you can share with me an image as a test drop.

**Comment by alok87** [comment]
@AmeerAssi Please try it out just pushed and image. Thank you for your patience.

`pushed: practodev/workerpodautoscaler:v1.0.0-30-g4b76774`
