### ISSUE TITLE
Do we consider the readiness time of the pod while scaling up?

### ISSUE THREAD

**Issue by jotish** [practo/k8s-worker-pod-autoscaler#67]

**Comment by alok87** [comment]
@jotish can you please elaborate more in the description. Not very clear. Lost the context.

**Comment by AmeerAssi** [comment]
I think I have also experienced this.
when a pod taking a lot of time until ready, the auto-scaler "thinks" that the pod already consuming jobs, although its not the case.
this causes wrong scaling problems.
I've reported an issue here:
https://github.com/practo/k8s-worker-pod-autoscaler/issues/101

**Comment by justjkk** [comment]
Currently the scaling happens based on available replicas. https://github.com/practo/k8s-worker-pod-autoscaler/pull/105/commits/f00ef3fc03b84337573a1047c65bc81a3dbe0866 in #105 changes this behavior so scaling happens based on spec replicas which includes both available and not ready replicas so that it doesn't scale up beyond the target.

**Comment by alok87** [comment]
Closed #102 as #105 fixes this problem

**Comment by alok87** [comment]
Pods no longer scale up on every tick(default 20seconds). It all depends on how many workers are needed to consumer the backlog(available)+reserved(inprocess) messages and the queue RPM. Closing this issue, as it solved now. @jotish
